export const SET_ACTIVE_RECEIVER = 'SET_ACTIVE_RECEIVER';

export const UPDATE_MESSAGE_HISTORY = 'UPDATE_MESSAGE_HISTORY';

export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS';


export const CLIENT_ID = 1337;

export const MESSAGE_TYPE = {
  SENT: 'SENT',
  RECEIVED: 'RECEIVED',
};